# Generated by Django 5.1.5 on 2025-07-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Individual Client', 'Individual Client'), ('Business Client', 'Business Client')], max_length=20)),
            ],
        ),
    ]
