# Generated by Django 5.1.5 on 2025-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completion_date', models.DateField()),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('to_do', models.JSONField(blank=True, default=list)),
                ('in_progress', models.JSONField(blank=True, default=list)),
                ('completed', models.JSONField(blank=True, default=list)),
                ('developers', models.JSONField(blank=True, default=list)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
    ]
