# Generated by Django 5.1.5 on 2025-07-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0001_initial'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client_management.client'),
            preserve_default=False,
        ),
    ]
