# Generated by Django 5.1 on 2025-07-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
    ]
